// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8HStMQXyDhcupNT82Dwj0UdWgO1E9TYs',
    appId: '1:409088882814:web:0f80207f65057a70a7c02f',
    messagingSenderId: '409088882814',
    projectId: 'campus-supply-abcbf',
    authDomain: 'campus-supply-abcbf.firebaseapp.com',
    storageBucket: 'campus-supply-abcbf.firebasestorage.app',
    measurementId: 'G-4YCF82KJ53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Rtz5SUBEJ8EEuzWTj06tJTHs3jfeDsA',
    appId: '1:409088882814:android:e66f1e62eaf16e56a7c02f',
    messagingSenderId: '409088882814',
    projectId: 'campus-supply-abcbf',
    storageBucket: 'campus-supply-abcbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIhnKeRXK7_6U1_mmD5HImc2eL4FFY1eo',
    appId: '1:409088882814:ios:67e6d3b20f582d1ca7c02f',
    messagingSenderId: '409088882814',
    projectId: 'campus-supply-abcbf',
    storageBucket: 'campus-supply-abcbf.firebasestorage.app',
    iosBundleId: 'com.example.campusSupply',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIhnKeRXK7_6U1_mmD5HImc2eL4FFY1eo',
    appId: '1:409088882814:ios:67e6d3b20f582d1ca7c02f',
    messagingSenderId: '409088882814',
    projectId: 'campus-supply-abcbf',
    storageBucket: 'campus-supply-abcbf.firebasestorage.app',
    iosBundleId: 'com.example.campusSupply',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8HStMQXyDhcupNT82Dwj0UdWgO1E9TYs',
    appId: '1:409088882814:web:8aad002b6c2ebf12a7c02f',
    messagingSenderId: '409088882814',
    projectId: 'campus-supply-abcbf',
    authDomain: 'campus-supply-abcbf.firebaseapp.com',
    storageBucket: 'campus-supply-abcbf.firebasestorage.app',
    measurementId: 'G-JHJT4M99ZP',
  );
}
